name: titan-secure-offline-app
version: '1.0.9'
summary: Node JS code for the Gateway
description: Changed Alert to Stored_Alert and Telemetry to Stored_Telemetry
confinement: strict
grade: devel

parts:
  titan-secure-offline-app:
    plugin: nodejs
    source: .
    build-packages:
      - libudev-dev
      - libbluetooth-dev
      - python
      - g++
      - make
      - bluez

apps:
  titan-secure-offline-app:
    command: bin/titan-secure-offline-app
    daemon: simple
    restart-condition: always
    plugs:
      - serial-port-067b2303
      - bluetooth-control
      - network-bind
      - network
      - network-control

plugs:
 serial-port-067b2303:
  interface: serial-port
